-- Priscilla Garcia pgarci40@calpoly.edu --
DROP TABLE IF EXISTS WINE;
DROP TABLE IF EXISTS GRAPES;
DROP TABLE IF EXISTS APPELLATION;

CREATE TABLE GRAPES(
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Grape VARCHAR(50) NOT NULL,
    Color VARCHAR(50) NOT NULL,
    UNIQUE(Grape)
);

CREATE TABLE APPELLATION(
    No INT AUTO_INCREMENT PRIMARY KEY,
    Appellation VARCHAR(50) NOT NULL,
    County VARCHAR(50),
    State VARCHAR(50) NOT NULL,
    Area VARCHAR(50) NOT NULL,
    isAVA VARCHAR(50) NOT NULL,
    UNIQUE(Appellation)
);

CREATE TABLE WINE(
    WineId INT PRIMARY KEY,
    Grape VARCHAR(50) NOT NULL,
    Winery VARCHAR(50) NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Appellation VARCHAR(50) NOT NULL,
    Year INT NOT NULL,
    Price DOUBLE NOT NULL,
    Score INT NOT NULL,
    Cases INT NOT NULL,
    CONSTRAINT fk_Wine_Grapes_Grape FOREIGN KEY (Grape) REFERENCES GRAPES(Grape),
    CONSTRAINT fk_Wine_Appellation_Appellation FOREIGN KEY (Appellation) REFERENCES APPELLATION(Appellation)
);
